CREATE DATABASE IF NOT EXISTS shopify;

CREATE TABLE IF NOT EXISTS `shopify`.`dim_date` (
  `date_key` int(10) DEFAULT NULL,
  `actual_date` date DEFAULT NULL,
  `week_start_date` date DEFAULT NULL,
  `week_end_date` date DEFAULT NULL,
  `week_number` int(10) DEFAULT NULL,
  `year` int(10) DEFAULT NULL,
  `day_of_week` varchar(10) DEFAULT NULL,
  `day_of_week_num` int(10) DEFAULT NULL,
  `day` int(10) DEFAULT NULL,
  `month` int(10) DEFAULT NULL,
  `quarter` int(10) DEFAULT NULL,
PRIMARY KEY (`date_key`) )
ENGINE=InnoDB;

DROP TABLE IF EXISTS `shopify`.`dim_product`;
CREATE TABLE IF NOT EXISTS `shopify`.`dim_product` (
  `product_id` VARCHAR(45) NULL ,
  `created_date_key` INT NULL ,
  `updated_date_key` INT NULL ,
  `published_date_key` INT NULL ,
  `created_on` DATETIME NULL ,
  `updated_on` DATETIME NULL ,
  `published_on` DATETIME NULL ,
  `handle` VARCHAR(255) NULL ,
  `name` VARCHAR(255) NULL ,
  `vendor` VARCHAR(255) NULL ,
  PRIMARY KEY (`product_id`) )
ENGINE = InnoDB;

DROP TABLE IF EXISTS `shopify`.`load_dim_product`;
CREATE TABLE IF NOT EXISTS `shopify`.`load_dim_product` (
  `product_id` VARCHAR(45) NULL ,
  `created_date_key` INT NULL ,
  `updated_date_key` INT NULL ,
  `published_date_key` INT NULL ,
  `created_on` DATETIME NULL ,
  `updated_on` DATETIME NULL ,
  `published_on` DATETIME NULL ,
  `handle` VARCHAR(255) NULL ,
  `name` VARCHAR(255) NULL ,
  `vendor` VARCHAR(255) NULL ,
  PRIMARY KEY (`product_id`) )
ENGINE = InnoDB;

DROP TABLE IF EXISTS `shopify`.`dim_sku`;
CREATE TABLE IF NOT EXISTS `shopify`.`dim_sku` (
  `sku_code` VARCHAR(255) NULL ,
  `sku_id` VARCHAR(45) NULL ,
  `sku_name` VARCHAR(255) NULL ,
  `created_date_key` INT NULL ,
  `updated_date_key` INT NULL ,
  `created_on` DATETIME NULL ,
  `updated_on` DATETIME NULL ,
  `color` VARCHAR(45) NULL ,
  `size` VARCHAR(45) NULL ,
  `shopify_inventory_quantity` INT NULL ,
  `shopify_inventory_management` VARCHAR(255) NULL ,
  `shopify_inventory_policy` VARCHAR(255) NULL ,
  `price` DECIMAL(10,2) NULL ,
  `compare_at_price` DECIMAL(10,2) NULL ,
  `taxable` TINYINT(1) NULL ,
  `weight_in_grams` FLOAT NULL ,
  `weight_in_lbs` FLOAT NULL ,
  `product_id` VARCHAR(45) NULL ,
  `product_name` VARCHAR(255) NULL ,
  `vendor` VARCHAR(45) NULL ,
  PRIMARY KEY (`sku_id`) )
ENGINE = InnoDB;

DROP TABLE IF EXISTS `shopify`.`load_dim_sku`;
CREATE TABLE IF NOT EXISTS `shopify`.`load_dim_sku` (
  `sku_code` VARCHAR(255) NULL ,
  `sku_id` VARCHAR(45) NULL ,
  `sku_name` VARCHAR(255) NULL ,
  `created_date_key` INT NULL ,
  `updated_date_key` INT NULL ,
  `created_on` DATETIME NULL ,
  `updated_on` DATETIME NULL ,
  `color` VARCHAR(45) NULL ,
  `size` VARCHAR(45) NULL ,
  `shopify_inventory_quantity` INT NULL ,
  `shopify_inventory_management` VARCHAR(255) NULL ,
  `shopify_inventory_policy` VARCHAR(255) NULL ,
  `price` DECIMAL(10,2) NULL ,
  `compare_at_price` DECIMAL(10,2) NULL ,
  `taxable` TINYINT(1) NULL ,
  `weight_in_grams` FLOAT NULL ,
  `weight_in_lbs` FLOAT NULL ,
  `product_id` VARCHAR(45) NULL ,
  `product_name` VARCHAR(255) NULL ,
  `vendor` VARCHAR(45) NULL ,
  PRIMARY KEY (`sku_id`) )
ENGINE = InnoDB;

DROP TABLE IF EXISTS `shopify`.`dim_order`;
CREATE TABLE IF NOT EXISTS `shopify`.`dim_order` (
  `order_id` VARCHAR(45) NULL ,
  `order_number` VARCHAR(45) NULL ,
  `customer_id` VARCHAR(45) NULL ,
  `email` VARCHAR(255) NULL ,
  `created_date_key` INT NULL ,
  `updated_date_key` INT NULL ,
  `ordered_date_key` INT NULL ,
  `closed_date_key` INT NULL ,
  `cancelled_date_key` INT NULL ,
  `created_on` TIMESTAMP NULL ,
  `updated_on` TIMESTAMP NULL ,
  `ordered_on` TIMESTAMP NULL ,
  `closed_on` TIMESTAMP NULL ,
  `cancelled_on` TIMESTAMP NULL ,
  `total_price` DECIMAL(10,2) NULL ,
  `total_line_items_price` DECIMAL(10,2) NULL ,
  `subtotal_price` DECIMAL(10,2) NULL ,
  `total_tax` DECIMAL(10,2) NULL ,
  `total_discounts` DECIMAL(10,2) NULL ,
  `total_shipping` DECIMAL(10,2) NULL ,
  `total_weight_in_grams` FLOAT NULL ,
  `total_weight_in_lbs` FLOAT NULL ,
  `currency` VARCHAR(3) NULL ,
  `credit_card_company` VARCHAR(45) NULL ,
  `payment_gateway` VARCHAR(45) NULL ,
  `financial_status` VARCHAR(45) NULL ,
  `fulfillment_status` VARCHAR(45) NULL ,
  `is_revenue` TINYINT(1) NULL ,
  `used_discount_code` TINYINT(1) NULL ,
  `shipping_method` VARCHAR(45) NULL ,
  `shipping_first_name` VARCHAR(255) NULL ,
  `shipping_last_name` VARCHAR(255) NULL ,
  `shipping_phone_number` VARCHAR(45) NULL ,
  `shipping_address1` VARCHAR(255) NULL ,
  `shipping_address2` VARCHAR(255) NULL ,
  `shipping_city` VARCHAR(255) NULL ,
  `shipping_zip` VARCHAR(255) NULL ,
  `shipping_province` VARCHAR(255) NULL ,
  `shipping_province_code` VARCHAR(45) NULL ,
  `shipping_country` VARCHAR(255) NULL ,
  `shipping_country_code` VARCHAR(45) NULL ,
  `shipping_latitude` FLOAT(10,4) NULL ,
  `shipping_longitude` FLOAT(10,4) NULL ,
  `shipping_company` VARCHAR(255) NULL ,
  `billing_first_name` VARCHAR(255) NULL ,
  `billing_last_name` VARCHAR(255) NULL ,
  `billing_phone_number` VARCHAR(45) NULL ,
  `billing_address1` VARCHAR(255) NULL ,
  `billing_address2` VARCHAR(255) NULL ,
  `billing_city` VARCHAR(255) NULL ,
  `billing_zip` VARCHAR(255) NULL ,
  `billing_province` VARCHAR(255) NULL ,
  `billing_province_code` VARCHAR(45) NULL ,
  `billing_country` VARCHAR(255) NULL ,
  `billing_country_code` VARCHAR(45) NULL ,
  `billing_latitude` FLOAT(10,4) NULL ,
  `billing_longitude` FLOAT(10,4) NULL ,
  `billing_company` VARCHAR(255) NULL ,
  `shopify_landing_site` TEXT NULL ,
  `shopify_landing_site_ref` TEXT NULL ,
  `shopify_referring_site` TEXT NULL ,
  `token` VARCHAR(45) NULL ,
  PRIMARY KEY (`order_id`))
ENGINE = InnoDB;

DROP TABLE IF EXISTS `shopify`.`load_dim_order`;
CREATE TABLE IF NOT EXISTS `shopify`.`load_dim_order` (
  `order_id` VARCHAR(45) NULL ,
  `order_number` VARCHAR(45) NULL ,
  `customer_id` VARCHAR(45) NULL ,
  `email` VARCHAR(255) NULL ,
  `created_date_key` INT NULL ,
  `updated_date_key` INT NULL ,
  `ordered_date_key` INT NULL ,
  `closed_date_key` INT NULL ,
  `cancelled_date_key` INT NULL ,
  `created_on` TIMESTAMP NULL ,
  `updated_on` TIMESTAMP NULL ,
  `ordered_on` TIMESTAMP NULL ,
  `closed_on` TIMESTAMP NULL ,
  `cancelled_on` TIMESTAMP NULL ,
  `total_price` DECIMAL(10,2) NULL ,
  `total_line_items_price` DECIMAL(10,2) NULL ,
  `subtotal_price` DECIMAL(10,2) NULL ,
  `total_tax` DECIMAL(10,2) NULL ,
  `total_discounts` DECIMAL(10,2) NULL ,
  `total_shipping` DECIMAL(10,2) NULL ,
  `total_weight_in_grams` FLOAT NULL ,
  `total_weight_in_lbs` FLOAT NULL ,
  `currency` VARCHAR(3) NULL ,
  `credit_card_company` VARCHAR(45) NULL ,
  `payment_gateway` VARCHAR(45) NULL ,
  `financial_status` VARCHAR(45) NULL ,
  `fulfillment_status` VARCHAR(45) NULL ,
  `is_revenue` TINYINT(1) NULL ,
  `used_discount_code` TINYINT(1) NULL ,
  `shipping_method` VARCHAR(45) NULL ,
  `shipping_first_name` VARCHAR(255) NULL ,
  `shipping_last_name` VARCHAR(255) NULL ,
  `shipping_phone_number` VARCHAR(45) NULL ,
  `shipping_address1` VARCHAR(255) NULL ,
  `shipping_address2` VARCHAR(255) NULL ,
  `shipping_city` VARCHAR(255) NULL ,
  `shipping_zip` VARCHAR(255) NULL ,
  `shipping_province` VARCHAR(255) NULL ,
  `shipping_province_code` VARCHAR(45) NULL ,
  `shipping_country` VARCHAR(255) NULL ,
  `shipping_country_code` VARCHAR(45) NULL ,
  `shipping_latitude` FLOAT(10,4) NULL ,
  `shipping_longitude` FLOAT(10,4) NULL ,
  `shipping_company` VARCHAR(255) NULL ,
  `billing_first_name` VARCHAR(255) NULL ,
  `billing_last_name` VARCHAR(255) NULL ,
  `billing_phone_number` VARCHAR(45) NULL ,
  `billing_address1` VARCHAR(255) NULL ,
  `billing_address2` VARCHAR(255) NULL ,
  `billing_city` VARCHAR(255) NULL ,
  `billing_zip` VARCHAR(255) NULL ,
  `billing_province` VARCHAR(255) NULL ,
  `billing_province_code` VARCHAR(45) NULL ,
  `billing_country` VARCHAR(255) NULL ,
  `billing_country_code` VARCHAR(45) NULL ,
  `billing_latitude` FLOAT(10,4) NULL ,
  `billing_longitude` FLOAT(10,4) NULL ,
  `billing_company` VARCHAR(255) NULL ,
  `shopify_landing_site` TEXT NULL ,
  `shopify_landing_site_ref` TEXT NULL ,
  `shopify_referring_site` TEXT NULL ,
  `token` VARCHAR(45) NULL ,
  PRIMARY KEY (`order_id`))
ENGINE = InnoDB;

DROP TABLE IF EXISTS `shopify`.`fact_order_line`;
CREATE TABLE IF NOT EXISTS `shopify`.`fact_order_line` (
  `order_line_id` VARCHAR(45) NULL ,
  `order_id` VARCHAR(45) NULL ,
  `product_id` VARCHAR(45) NULL ,
  `sku_id` VARCHAR(45) NULL ,
  `fulfillment_id` VARCHAR(45) NULL ,
  `customer_id` VARCHAR(45) NULL ,
  `ordered_date_key` INT NULL ,
  `sku_code` VARCHAR(255) NULL ,
  `quantity` INT NULL ,
  `price` DECIMAL(10,2) NULL ,
  `gross_extended_price` DECIMAL(10,2) NULL ,
  `net_extended_price` DECIMAL(10,2) NULL ,
  `weight_in_grams` FLOAT NULL ,
  `weight_in_lbs` FLOAT NULL ,
  `fulfillment_status` VARCHAR(45) NULL ,
  `fulfillment_service` VARCHAR(45) NULL ,
  `currency` VARCHAR(3) NULL ,
  `oh_financial_status` VARCHAR(45) NULL ,
  `oh_fulfillment_status` VARCHAR(45) NULL ,
  `oh_created_on` TIMESTAMP NULL ,
  `oh_updated_on` TIMESTAMP NULL ,
  `oh_ordered_on` TIMESTAMP NULL ,
  `oh_closed_on` TIMESTAMP NULL ,
  `oh_cancelled_on` TIMESTAMP NULL ,
  PRIMARY KEY (`order_id`, `order_line_id`) )
ENGINE = InnoDB;

DROP TABLE IF EXISTS `shopify`.`load_fact_order_line`;
CREATE TABLE IF NOT EXISTS `shopify`.`load_fact_order_line` (
  `order_line_id` VARCHAR(45) NULL ,
  `order_id` VARCHAR(45) NULL ,
  `product_id` VARCHAR(45) NULL ,
  `sku_id` VARCHAR(45) NULL ,
  `fulfillment_id` VARCHAR(45) NULL ,
  `customer_id` VARCHAR(45) NULL ,
  `ordered_date_key` INT NULL ,
  `sku_code` VARCHAR(255) NULL ,
  `quantity` INT NULL ,
  `price` DECIMAL(10,2) NULL ,
  `gross_extended_price` DECIMAL(10,2) NULL ,
  `net_extended_price` DECIMAL(10,2) NULL ,
  `weight_in_grams` FLOAT NULL ,
  `weight_in_lbs` FLOAT NULL ,
  `fulfillment_status` VARCHAR(45) NULL ,
  `fulfillment_service` VARCHAR(45) NULL ,
  `currency` VARCHAR(3) NULL ,
  `oh_financial_status` VARCHAR(45) NULL ,
  `oh_fulfillment_status` VARCHAR(45) NULL ,
  `oh_created_on` TIMESTAMP NULL ,
  `oh_updated_on` TIMESTAMP NULL ,
  `oh_ordered_on` TIMESTAMP NULL ,
  `oh_closed_on` TIMESTAMP NULL ,
  `oh_cancelled_on` TIMESTAMP NULL ,
  PRIMARY KEY (`order_id`, `order_line_id`) )
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `shopify`.`lk_prd_to_cat` (
  `product_key` INT NOT NULL ,
  `product_id` VARCHAR(45) NULL ,
  `merch_cat_key` INT NULL ,
  `merch_cat_path` VARCHAR(255) NULL ,
  PRIMARY KEY (`product_key`) )
ENGINE = InnoDB;

CREATE  TABLE IF NOT EXISTS `shopify`.`dim_merch_category` (
  `merch_cat_key` INT NOT NULL ,
  `merch_cat_name` VARCHAR(100) NULL ,
  `merch_cat_path` VARCHAR(255) NULL ,
  `parent_merch_cat_key` VARCHAR(255) NULL ,
  `parent_merch_cat_path` VARCHAR(255) NULL ,
  `level1` VARCHAR(255) NULL ,
  `level2` VARCHAR(255) NULL ,
  `level3` VARCHAR(255) NULL ,
  `level4` VARCHAR(255) NULL ,
  `level5` VARCHAR(255) NULL ,
  PRIMARY KEY (`merch_cat_key`) )
ENGINE = InnoDB;