INSERT INTO fact_order_line
(
order_line_id,
order_id,
product_id,
sku_id,
fulfillment_id,
customer_id,
ordered_date_key,
sku_code,
quantity,
price,
gross_extended_price,
net_extended_price,
weight_in_grams,
weight_in_lbs,
fulfillment_status,
fulfillment_service,
currency,
oh_financial_status,
oh_fulfillment_status,
oh_created_on,
oh_updated_on,
oh_ordered_on,
oh_closed_on,
oh_cancelled_on
)
SELECT
order_line_id,
order_id,
product_id,
sku_id,
fulfillment_id,
customer_id,
ordered_date_key,
sku_code,
quantity,
price,
gross_extended_price,
net_extended_price,
weight_in_grams,
weight_in_lbs,
fulfillment_status,
fulfillment_service,
currency,
oh_financial_status,
oh_fulfillment_status,
oh_created_on,
oh_updated_on,
oh_ordered_on,
oh_closed_on,
oh_cancelled_on
FROM
load_fact_order_line evt
ON DUPLICATE KEY UPDATE
product_id = evt.product_id,
sku_id = evt.sku_id,
fulfillment_id = evt.fulfillment_id,
customer_id = evt.customer_id,
ordered_date_key = evt.ordered_date_key,
sku_code = evt.sku_code,
quantity = evt.quantity,
price = evt.price,
gross_extended_price = evt.gross_extended_price,
net_extended_price = evt.net_extended_price,
weight_in_grams = evt.weight_in_grams,
weight_in_lbs = evt.weight_in_lbs,
fulfillment_status = evt.fulfillment_status,
fulfillment_service = evt.fulfillment_service,
currency = evt.currency,
oh_financial_status = evt.oh_financial_status,
oh_fulfillment_status = evt.oh_fulfillment_status,
oh_created_on = evt.oh_created_on,
oh_updated_on = evt.oh_updated_on,
oh_ordered_on = evt.oh_ordered_on,
oh_closed_on = evt.oh_closed_on,
oh_cancelled_on = evt.oh_cancelled_on
;