INSERT INTO shopify.dim_sku
(
sku_code,
sku_id,
sku_name,
created_date_key,
updated_date_key,
created_on,
updated_on,
color,
size,
shopify_inventory_quantity,
shopify_inventory_management,
shopify_inventory_policy,
price,
compare_at_price,
taxable,
weight_in_grams,
weight_in_lbs,
product_id,
product_name,
vendor
)
SELECT 
sku_code,
sku_id,
sku_name,
created_date_key,
updated_date_key,
created_on,
updated_on,
color,
size,
shopify_inventory_quantity,
shopify_inventory_management,
shopify_inventory_policy,
price,
compare_at_price,
taxable,
weight_in_grams,
weight_in_lbs,
product_id,
product_name,
vendor
FROM load_dim_sku evt
ON DUPLICATE KEY UPDATE
sku_code = evt.sku_code,
sku_name = evt.sku_name,
created_date_key = evt.created_date_key,
updated_date_key = evt.updated_date_key,
created_on = evt.created_on,
updated_on = evt.updated_on,
color = evt.color,
size = evt.size,
shopify_inventory_quantity = evt.shopify_inventory_quantity,
shopify_inventory_management = evt.shopify_inventory_management,
shopify_inventory_policy = evt.shopify_inventory_policy,
price = evt.price,
compare_at_price = evt.compare_at_price,
taxable = evt.taxable,
weight_in_grams = evt.weight_in_grams,
weight_in_lbs = evt.weight_in_lbs,
product_id = evt.product_id,
product_name = evt.product_name,
vendor = evt.vendor
;
