INSERT INTO dim_order
(
order_id,
order_number,
customer_id,
created_date_key,
updated_date_key,
ordered_date_key,
closed_date_key,
cancelled_date_key,
created_on,
updated_on,
ordered_on,
closed_on,
cancelled_on,
total_price,
total_line_items_price,
subtotal_price,
total_tax,
total_discounts,
total_shipping,
total_weight_in_grams,
total_weight_in_lbs,
currency,
credit_card_company,
payment_gateway,
financial_status,
fulfillment_status,
is_revenue,
used_discount_code,
shipping_method,
shipping_first_name,
shipping_last_name,
shipping_phone_number,
shipping_address1,
shipping_address2,
shipping_city,
shipping_zip,
shipping_province,
shipping_province_code,
shipping_country,
shipping_country_code,
shipping_latitude,
shipping_longitude,
shipping_company,
billing_first_name,
billing_last_name,
billing_phone_number,
billing_address1,
billing_address2,
billing_city,
billing_zip,
billing_province,
billing_province_code,
billing_country,
billing_country_code,
billing_latitude,
billing_longitude,
billing_company,
shopify_landing_site,
shopify_landing_site_ref,
shopify_referring_site,
token,
email
)
SELECT
order_id,
order_number,
customer_id,
created_date_key,
updated_date_key,
ordered_date_key,
closed_date_key,
cancelled_date_key,
created_on,
updated_on,
ordered_on,
closed_on,
cancelled_on,
total_price,
total_line_items_price,
subtotal_price,
total_tax,
total_discounts,
total_shipping,
total_weight_in_grams,
total_weight_in_lbs,
currency,
credit_card_company,
payment_gateway,
financial_status,
fulfillment_status,
is_revenue,
used_discount_code,
shipping_method,
shipping_first_name,
shipping_last_name,
shipping_phone_number,
shipping_address1,
shipping_address2,
shipping_city,
shipping_zip,
shipping_province,
shipping_province_code,
shipping_country,
shipping_country_code,
shipping_latitude,
shipping_longitude,
shipping_company,
billing_first_name,
billing_last_name,
billing_phone_number,
billing_address1,
billing_address2,
billing_city,
billing_zip,
billing_province,
billing_province_code,
billing_country,
billing_country_code,
billing_latitude,
billing_longitude,
billing_company,
shopify_landing_site,
shopify_landing_site_ref,
shopify_referring_site,
token,
email
FROM load_dim_order evt
ON DUPLICATE KEY UPDATE
order_number = evt.order_number,
customer_id = evt.customer_id,
created_date_key = evt.created_date_key,
updated_date_key = evt.updated_date_key,
ordered_date_key = evt.ordered_date_key,
closed_date_key = evt.closed_date_key,
cancelled_date_key = evt.cancelled_date_key,
created_on = evt.created_on,
updated_on = evt.updated_on,
ordered_on = evt.ordered_on,
closed_on = evt.closed_on,
cancelled_on = evt.cancelled_on,
total_price = evt.total_price,
total_line_items_price = evt.total_line_items_price,
subtotal_price = evt.subtotal_price,
total_tax = evt.total_tax,
total_discounts = evt.total_discounts,
total_shipping = evt.total_shipping,
total_weight_in_grams = evt.total_weight_in_grams,
total_weight_in_lbs = evt.total_weight_in_lbs,
currency = evt.currency,
credit_card_company = evt.credit_card_company,
payment_gateway = evt.payment_gateway,
financial_status = evt.financial_status,
fulfillment_status = evt.fulfillment_status,
is_revenue = evt.is_revenue,
used_discount_code = evt.used_discount_code,
shipping_method = evt.shipping_method,
shipping_first_name = evt.shipping_first_name,
shipping_last_name = evt.shipping_last_name,
shipping_phone_number = evt.shipping_phone_number,
shipping_address1 = evt.shipping_address1,
shipping_address2 = evt.shipping_address2,
shipping_city = evt.shipping_city,
shipping_zip = evt.shipping_zip,
shipping_province = evt.shipping_province,
shipping_province_code = evt.shipping_province_code,
shipping_country = evt.shipping_country,
shipping_country_code = evt.shipping_country_code,
shipping_latitude = evt.shipping_latitude,
shipping_longitude = evt.shipping_longitude,
shipping_company = evt.shipping_company,
billing_first_name = evt.billing_first_name,
billing_last_name = evt.billing_last_name,
billing_phone_number = evt.billing_phone_number,
billing_address1 = evt.billing_address1,
billing_address2 = evt.billing_address2,
billing_city = evt.billing_city,
billing_zip = evt.billing_zip,
billing_province = evt.billing_province,
billing_province_code = evt.billing_province_code,
billing_country = evt.billing_country,
billing_country_code = evt.billing_country_code,
billing_latitude = evt.billing_latitude,
billing_longitude = evt.billing_longitude,
billing_company = evt.billing_company,
shopify_landing_site = evt.shopify_landing_site,
shopify_landing_site_ref = evt.shopify_landing_site_ref,
shopify_referring_site = evt.shopify_referring_site,
token = evt.token,
email = evt.email
;